name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 15 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download And Install
      run: curl -sL https://ibm.biz/idt-installer | bash
      
    - name: Login IBM Cloud
      run: |
        ibmcloud login -u ${{ secrets.MAIL }} -p ${{ secrets.PWD }} -r ${{ secrets.RGN }}
    - name: Do My Jobs
      run: |
        ibmcloud target -g Default
        ibmcloud target --cf
        ibmcloud cf install
        ibmcloud cf restart ${{ secrets.CFNAME }}
